version: '3.9'

services:
  db:
    image: postgres:13.5-alpine
    container_name: rocks_fuckers_db
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file: .env
    restart: always

  bot:
    container_name: rocks_fuckers_bot
    build: .
    image: bots/rocks_fuckers_bot
    volumes:
      - ./data:/opt/rocks_fuckers_bot/data
    env_file: .env
    restart: always
    depends_on: [db]

volumes:
  db_data: {}
